---
name: Lint
on:
  push:
    # branches: ["NEVER"]
  pull_request:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  Lint:
    uses: dennykorsukewitz/dennykorsukewitz/.github/workflows/reusable.lint.yml@dev
    with:
      VALIDATE_PYTHON_BLACK: false
      VALIDATE_PYTHON_FLAKE8: false
      VALIDATE_PYTHON_ISORT: false
      VALIDATE_PYTHON_PYLINT: false
      VALIDATE_BIOME_FORMAT: false
      VALIDATE_BIOME_LINT: false
      VALIDATE_EDITORCONFIG: false
      VALIDATE_NATURAL_LANGUAGE: false
      VALIDATE_PYTHON_RUFF: false
      VALIDATE_PYTHON_RUFF_FORMAT: false
      VALIDATE_SPELL_CODESPELL: false
      VALIDATE_MARKDOWN: false
      VALIDATE_MARKDOWN_PRETTIER: false
