---
name: Release
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:

  Release-GitHub:
    name: Release GitHub
    environment:
      name: Release GitHub
      url: "https://github.com/dennykorsukewitz?tab=packages&repo_name=generator-sublime-package"
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'

          # Defaults to the user or organization that owns the workflow file
          scope: '@dennykorsukewitz'
      - name: npm install
        run: npm i
      - name: npm clean-install
        run: npm ci
      - run: npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}